name: Deploy manifest to exchange and upload files to azure

on:
  push:
    branches:
      - main
      - US31/Backend_Service_Demo
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    env:
      AZ_STORAGE_ACCOUNT_KEY: ${{ secrets.AZ_STORAGE_ACCOUNT_KEY }}
      APP_CLIENT_ID: ${{ secrets.APP_CLIENT_ID }}
      APP_CLIENT_SECRET: ${{ secrets.APP_CLIENT_SECRET }}
      APP_TENANT_ID: ${{ secrets.APP_TENANT_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: upload files
        if: false
        run: |
          mkdir upload
          mv manifest.xml upload
          mv src\commands\* upload
          mv src\taskpane\* upload
          mv assets\* upload

          az storage blob upload-batch `
          --account-name coderbois `
          --account-key "$env:AZ_STORAGE_ACCOUNT_KEY" `
          --destination add-in `
          --source upload `
          --overwrite `
          --pattern="*"

      - name: Deploy manifest to exchange
        #install required modules

        #Install-Module -Name Microsoft.Authentication.Identity.Client -Force -Scope CurrentUser
        #Import-Module ExchangeOnlineManagement
        run: |
          Install-Module -Name ExchangeOnlineManagement -Force -AllowClobber
          Import-Module ExchangeOnlineManagement
          
          $clientId = $env:APP_CLIENT_ID
          $clientSecret = $env:APP_CLIENT_SECRET
          $tenantId = $env:APP_TENANT_ID

          $secPassword = ConvertTo-SecureString $clientSecret -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential ($clientId, $secPassword)

          Connect-ExchangeOnline -Credential $credential

      


        


  
