name: Deploy manifest to exchange and upload files to azure

on:
  push:
    branches:
      - main
      - US31/Backend_Service_Demo
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    env:
      AZ_STORAGE_ACCOUNT_KEY: ${{ secrets.AZ_STORAGE_ACCOUNT_KEY }}
      APP_CLIENT_ID: ${{ secrets.APP_CLIENT_ID }}
      APP_TENANT_ID: ${{ secrets.APP_TENANT_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: setup azure for powershell
        #authenticate and create context
        run: |
          $storageAccountName="coderbois"
          $containerName="add-in"

          mkdir upload
          cp manifest.xml .\upload
          cp assets .\upload
          cp src .\upload

          az storage blob upload-batch --account-name $storageAccountName --account-key $AZ_STORAGE_ACCOUNT_KEY --destination $containerName --source .\upload\*

      - name: setup exchange for powershell
        #install required modules
        run: |
          Install-Module -Name Microsoft.Authentication.Identity.Client -Force -Scope CurrentUser
          Import-Module ExchangeOnlineManagement

          $authority = "https://login.microsoftonline.com/$APP_TENANT_ID"
          $scopes = "https://outlook.office365.com/.default"

          $msalClient = New-Object Microsoft.Identity.Client.PublicClientApplication -ArgumentList $APP_CLIENT_ID, $authority
          $token = $msalClient.AcquireTokenInteractive($scopes).ExecuteAsync().Result
          
          Connect-ExchangeOnline -AccessToken $token.AccessToken
      


        


  
