name: Deploy manifest to exchange and upload files to azure

on:
  push:
    branches:
      - main
      - US31/Backend_Service_Demo
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    env:
      AZ_STORAGE_ACCOUNT_KEY: ${{ secrets.AZ_STORAGE_ACCOUNT_KEY }}
      APP_CLIENT_ID: ${{ secrets.APP_CLIENT_ID }}
      APP_TENANT_ID: ${{ secrets.APP_TENANT_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: upload files
        run: |
          $files = @("\.manifest.xml", "\.src/commands", "\.src/taskpane", "\.assets")
          foreach ($file in $files) {
            echo $file
            az storage blob upload-batch `
            --account-name coderbois `
            --account-key "$env:AZ_STORAGE_ACCOUNT_KEY" `
            --destination add-in `
            --source $file `
            --overwrite `
            --pattern="*"
          }

      - name: Deploy manifest to exchange
        #install required modules

        #Install-Module -Name Microsoft.Authentication.Identity.Client -Force -Scope CurrentUser
        #Import-Module ExchangeOnlineManagement
        run: |
          $authority = "https://login.microsoftonline.com/$env:APP_TENANT_ID"
          $scopes = "https://outlook.office365.com/.default"

          $msalClient = New-Object Microsoft.Identity.Client.PublicClientApplication -ArgumentList $env:APP_CLIENT_ID, $authority
          $token = $msalClient.AcquireTokenInteractive($scopes).ExecuteAsync().Result
          
          Connect-ExchangeOnline -AccessToken $token.AccessToken
      


        


  
